services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: demo-spring-boot
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init-data:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmqdefaultuser
      RABBITMQ_DEFAULT_PASS: rabbitmqdefaultpass
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  postgres_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local